### ISSUE TITLE
Two XSS vulnerabilities in latest Gila CMS (2.1.0 version)

### ISSUE THREAD

**Issue by victomteng1997** [GilaCMS/gila#127]
I have contacted the developer by following the security vulnerability policy, but didn't receive any reply for 7 days.

**Vulnerability 1: Reflected XSS**
Reflected XSS through `fm/upload` endpoint with filename parameter.
Vulnerable code at `uploadAction` function in `src/core/controllers/FMController.php`:

```
for ($i=0; $i<count($tmp_file); $i++) {
      if (!FileManager::allowedFileType($name[$i])) {
        die("Error: File type {$name[$i]} is not accepted!");
      }
      if (!move_uploaded_file($tmp_file[$i], SITE_PATH.$path.'/'.$name[$i])) {
        die("Error: could not upload file!");
      }
    }
```
The filename $name is not properly filtered. 

**To Reproduce**
Attacker with file upload access can upload a file with a disallowed extension (.php, etc.)  that contains xss payload, for example `"><svg onload=alert(1)>".py` to trigger the target code block. This results in a reflected XSS.

![gila_reflected_xss](https://user-images.githubusercontent.com/25191772/121460652-e31ab380-c9df-11eb-8d33-357358fab437.gif)

**System Information**
 - OS: Ubuntu 20.04
 - Browser: firefox ubuntu default version. 

**Vulnerability 2: Stored XSS**

The vulnerable code block is at `dirAction()` function in `src/core/controllers/FMController.php`:

```
  public function dirAction()
  {
    \\ some codes here
    
    $folderinfo['files'] = $filelist;
    $folderinfo['path'] = $this->relativePath;
    echo json_encode($folderinfo);
  }
```
In short, the above function returns the files information of the requested folder in a json format:
```
{files: [{'name': 'file1', 'size':1, 'mtime': 'time', 'mode': mode, 'ext': '.txt'}, {file2, ....}, ...], 'path': 'log'}
```
When uploading a file, the attacker can control the filename variable. 

**To Reproduce**
The attacker can upload a file with valid file extension but a malicious filename, such as `"><svg onload=alert(1)>".txt` to the directory that he has access to, for example './log/'. Later when any other user access the webpage to browse the files in this folder through `fm/dir?path=log` endpoint, the stored XSS content is triggered. This can be shown in the following (gila_stored_xss.gif). 

![gila_stored_xss](https://user-images.githubusercontent.com/25191772/121460911-5f14fb80-c9e0-11eb-87ad-fbda53dcc4ff.gif)

**System Information**
 - OS: Ubuntu 20.04
 - Browser: firefox ubuntu default version.

**Comment by vzuburlis** [comment]
Thank you for the finds

The issues will be resolved in version 2.2.0
