### ISSUE TITLE
Where is the Ecommerce

### ISSUE THREAD

**Issue by TheTechRobo** [GilaCMS/gila#130]
**Is your feature request related to a problem? Please describe.**
I see in the tags that there is ecommerce But there doesn't seem to be

**Describe the solution you'd like**
either a guide on how to add ecommerce or actually adding it if isn't there

**Describe alternatives you've considered**
lying in the github tags. Or removing from the github tags.

**Additional context**
![image](https://user-images.githubusercontent.com/52163910/125518334-55a59c33-418a-4fcc-9a4a-b566a18c766d.png)

**Comment by vzuburlis** [comment]
The eshop package is out of date, since it is not supported anymore, the tag will be removed.
