### ISSUE TITLE
Widget links accept tags

### ISSUE THREAD

**Issue by vzuburlis** [GilaCMS/gila#23]
A XSS vulnerability has been found with widget 'links'. The fields accept the script tags

To reproduce:
1. Create a link widget at /admin/content/widget
2. Add "<script>alert(0)</script>" as text in a link.
3. Set widget are the dashboard
4. Go to dashboard: /admin

Solution:
Links widget uses the 'list' component.
We need to use strip_tags() before the values are stored.

**Comment by vzuburlis** [comment]
@KotatuBot reported that actually all fields from widgets are vulnerable.
So the solution is to strip tags for every field, make exceptions for some text fields that have to be stored in html.

**Comment by panigrc** [comment]
As you moved this in **Done** in **Content Editing** you should probably close this issue.
