### ISSUE TITLE
Use a module bundler for javascript/css assets

### ISSUE THREAD

**Issue by panigrc** [GilaCMS/gila#44]
To make Gila more maintainable I propose to use a module bundler i.ex. https://webpack.js.org

Because now all the javascript libraries are under `gila/lib` . The problem with that is that you need to update the libraries everytime manually and also manually load the scripts in the code.

**Comment by vzuburlis** [comment]
npm was initially used to download the latest versions and then with update-dep.sh copy them inside llb/ folder. If it sounds good I can reinstall nmp at development so its package.json can be included in the repo
