### ISSUE TITLE
[Security] Use a public or web directory 📁

### ISSUE THREAD

**Issue by panigrc** [GilaCMS/gila#45]
In order to increase security, the source code of the project shouldn't be exposed in the public directory of the web server.

That's why there should be a web or public directory in which all the public files are put.

- assets (images/css/js)
- `.htaccess` 
- `index.php`
- `robots.txt`

**Comment by vzuburlis** [comment]
Agree. The idea is to make private the src/ and theme/. Their assets will be copied on a public folder ex. 'assets/<package-name>/' when a package/theme is installed
