### ISSUE TITLE
Conventions content.css

### ISSUE THREAD

**Issue by vzuburlis** [GilaCMS/gila#6]
Make changes on file src/core/assets/admin/content.css to meet the following conventions:

- use 2 spaces for indentation (replace tabs)
- leave 1 empty line in the end of file
- use a space after ; when are inline
- use a space before {
- use 1 empty line instead of 2 between code blocks
- dont close the file with ?>

**Comment by asprazz** [comment]
Hie @vzuburlis I would like work on this ...:)

**Comment by asprazz** [comment]
Hi! just one quick question What if we converted inline to block styles ?

**Comment by asprazz** [comment]
Please let me know your thoughts, after I will send PR Thank You :1st_place_medal:

**Comment by vzuburlis** [comment]
Looks better :)
