### ISSUE TITLE
There is three file vulnerability that can read  arbitrary file,write arbitrary file,delete arbitrary file

### ISSUE THREAD

**Issue by Neikoxiuxian** [GilaCMS/gila#66]
After the administrator logs in, Gila CMS 1.11.8 does not filter the file read, file delete, and file write functions, resulting in arbitrary file read, delete, and write.
**The value of the parameter path can be any path**

arbitrary file read:
![renyiwenjianduqu2](https://user-images.githubusercontent.com/45188709/77997831-aa566780-7362-11ea-8bec-cea1e777e84e.png)
![renyiwenjianduqu3](https://user-images.githubusercontent.com/45188709/77997835-ad515800-7362-11ea-9c4d-bdc4b0720ca2.png)

arbitrary file write:
![renyiwenjianxieru1](https://user-images.githubusercontent.com/45188709/77997879-bfcb9180-7362-11ea-88ed-d55233c2af9d.png)
![renyiwenjianxieru2](https://user-images.githubusercontent.com/45188709/77997893-c5c17280-7362-11ea-82f0-9a36c911aac3.png)

arbitrary file delete:
![renyiwenjianshanchu1](https://user-images.githubusercontent.com/45188709/77997911-ceb24400-7362-11ea-9cea-b2fc9e20e9e9.png)

**Comment by vzuburlis** [comment]
Thank you @Neikoxiuxian for the report.
The /fm endpoint was actually created to edit php files (now it is also used from gallery to create folders etc)
It can edit files from the installation folder and below, and only user with the admin privilege can edit files.

I am going to add a template engine to the system, so admin will be able to change tmp/html files of the view files. Then /fm probably will be restricted on folders and type of files.

If you think that this vulnerability can be a threat to website (attacked without the knowledge of the admin), please comment your ideas, so I will add the template engine as priority.

**Comment by Neikoxiuxian** [comment]
Hello, glad to hear from you.

My English is not very good. I hope you can understand.

If an attacker obtains the cookie of admin, it is possible to perform any operation related to the file. It is equivalent to destroying the whole website.

The safest way is that even if you have an admin user, you should operate under certain files, not arbitrary files.

I think this is a vulnerability. Through the vulnerability, I even get all the config (including administrator account), modify arbitrary files, arbitrarily expose the source code and remotely modify arbitrary files.

If I get the admin cookie through XSS vulnerability, I can do anything. It's very unsafe.

I suggest that you modify the relevant issues in the next version. The file operation of admin should be limited to specific files. Just like files can only be uploaded under the asset folder, and the suffix is limited, which leads to my inability to upload malicious Trojans.

You cannot trust the input of any user, including the admin user.

**Comment by Neikoxiuxian** [comment]
Like you said after adding a template, changing the view file or something else should also be under some specific files, not arbitrary files.

It is too dangerous to read, modify, and write to any file.

Don't underestimate file operation permissions just because of the admin user.

The admin user should not have such rights

**Comment by vzuburlis** [comment]
Thank you, I leave the issue open until the version that removes the access in arbitary files.
